### ISSUE TITLE
ImportError: cannot import name '_app_ctx_stack' from 'flask'

### ISSUE THREAD

**Issue by arunas-v** [wuttem/flask-ad-auth#6]
from core import app  # Import your app
    ^^^^^^^^^^^^^^^^^^^^
  File "...\core\__init__.py", line 5, in <module>
    from flask_ad_auth import ADAuth
  File "...\venv\Lib\site-packages\flask_ad_auth\__init__.py", line 15, in <module>
    from .ad_login import ADAuth, ad_group_required, ad_required, User
  File "...\venv\Lib\site-packages\flask_ad_auth\ad_login.py", line 29, in <module>
    from flask import _app_ctx_stack as stack
ImportError: cannot import name '_app_ctx_stack' from 'flask' (...\venv\Lib\site-packages\flask\__init__.py)

# pip list
...
Flask              3.0.1
flask-ad-auth      0.8.2
Flask-Login        0.6.3
Flask-SQLAlchemy   3.1.1
...

**Comment by wuttem** [comment]
Seems like you are using version 0.8.2
That is the latest release on pypi - if you install from git you should get version 1.0.1 where i think this is already solved.
Could you try this ?
I will probably release version 1.0.1 to pypi soon - I just haven't done so yet because it breaks backwards compatibility.

**Comment by arunas-devoro** [comment]
Hi, Nope it is not solved. version 1.0.1 still want to import module that is not supported on Flask 3.0. I've already updated it. can do PR so you can review?

**Comment by wuttem** [comment]
Thank you!

I reviewed and created a change that also incorporates the current best practice of storing the db connection in g.
As seen here: https://flask.palletsprojects.com/en/3.0.x/appcontext/

Should be on the master branch (or tag v1.1.0) - can you check that this solves your problem ? I will push to Pypi afterwards.
I also saw that you fixed some stuff in the readme - can you do a new pull request for these changes - i will merge it so you also get the contribution credited.

**Comment by arunas-devoro** [comment]
Confirmed your updated GIT version v1.1.0 on master branch works with Flask v3.
p.s. documentation updated with new PR.

and thanks for the module. saved me a lot of time.

**Comment by arunas-devoro** [comment]
> Thank you!
> 
> I reviewed and created a change that also incorporates the current best practice of storing the db connection in g. As seen here: https://flask.palletsprojects.com/en/3.0.x/appcontext/
> 
> Should be on the master branch (or tag v1.1.0) - can you check that this solves your problem ? I will push to Pypi afterwards. I also saw that you fixed some stuff in the readme - can you do a new pull request for these changes - i will merge it so you also get the contribution credited.

Please when you have time update pypi ;)
Also you can close this issue.

**Comment by wuttem** [comment]
Done!
Thanks again!
